add_newline = false

format = """
$directory$git_branch$git_state$git_status\
$kubernetes\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$vlang\
$vagrant\
$zig\
$terraform
$time $username$hostname $nix_shell$character"""

[git_branch]
style = "bold green"
format = "[\\[[$branch$tag](bold green)\\]](bold white)"

[git_status]
format = ' ([\[$conflicted$deleted$renamed$modified$staged$untracked$ahead_behind\]]($style)) '

[hostname]
ssh_only = true
format = "@[$hostname]($style)"
style = "bold white"

[username]
show_always = true
format = "[$user]($style)"
style_user = "bold white"

[directory]
truncation_length = 5
truncation_symbol = ".../"
style = 'bold bright-blue'

[kubernetes]
disabled = false
format = 'on [\($symbol$context:$namespace\)](purple bold) '

[nix_shell]
disabled = false
impure_msg = "[impure shell](bold red)"
pure_msg = "[pure shell](bold green)"
format = '[\(nix: $state $name\)](bold blue) '

[terraform]
format = "via [$symbol$version](bold 105) "

[time]
disabled = false
format = "[$time]($style)"
time_format = "%H:%M"
