add_newline = false

format = """
$directory$git_branch$git_state$git_status\
$direnv\
$kubernetes\
$aws\
$terraform
$time $username$hostname $nix_shell$character"""


[aws]
format = 'on [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
symbol = '☁️ '
style = 'bold yellow'
disabled = false
expiration_symbol = 'X'
force_display = false

[direnv]
disabled = false

[git_branch]
style = "bold green"
format = "[\\[[$branch$tag](bold green)\\]](bold white)"

[git_status]
format = ' ([\[$conflicted$deleted$renamed$modified$staged$untracked$ahead_behind\]]($style)) '

[hostname]
ssh_only = true
format = "@[$hostname]($style)"
style = "bold white"

[username]
show_always = false
format = "[$user]($style)"
style_user = "bold white"

[directory]
truncation_length = 5
truncation_symbol = ".../"
style = 'bold bright-blue'

[kubernetes]
disabled = false
format = 'on [\($context:$namespace\)](purple bold) '

[nix_shell]
disabled = false
impure_msg = "[impure](bold red)"
pure_msg = "[pure](bold green)"
format = '[\(nix: $state $name\)](bold blue) '

[terraform]
format = "with [tf $version](bold 105) "
disabled = true

[time]
disabled = false
format = "[$time]($style)"
time_format = "%H:%M"

